---
title: "Instructed Spinal Segment Analysis"
author: "Andrew + Brendan"
format: html
editor: source
---

## Setup

```{r}
#| message: false
library(tidyverse)
library(here)
library(lubridate)
library(lme4)
library(MASS)
library(nlme)
library(car)
library(emmeans)
```

```{r}
instructed <- read_csv(here("data", "instructed.csv"))
```
## Data Cleaning

### Aggregating Data by Second for Instructed Section

```{r}
instructed_agg <- instructed %>%
  mutate(sec = floor(time)) %>%
  group_by(participant, device_location, posture, sec) %>%
  summarize(angle_x = mean(angle_x), .groups = "keep")
```

```{r}
instructed_agg_nested <- instructed %>%
  mutate(nested_sec = floor(nested_time)) %>%
  group_by(participant, device_location, posture, nested_sec) %>%
  summarize(angle_x = mean(angle_x), .groups = "keep")
```

### Create Dataset for Modeling

```{r}
#| message: false
model_data <- instructed_agg_nested %>% 
  filter(posture != "transition") %>%
  group_by(participant, device_location, posture) %>%
  summarize(angle_x = mean(angle_x, na.rm = TRUE)) %>%
  ungroup() %>%
  pivot_wider(id_cols = c(participant, posture), names_from = device_location, values_from = angle_x) %>%
  mutate(posture = if_else(str_detect(posture, "good"), "good", posture)) %>%
  ungroup() %>%
  rename(
    "lower_back" = 3,
    "mid_back" = 4,
    "neck" = 5
  )
```

### Create Dataset for Plots

```{r}
xmin <- c(0,10,14,24,27,37,41,51,54,64,67,77,80,90,93,103,106)
xmax <- lead(xmin,1)
xmax[17] <- 116
ymin <- rep(-70,17)
ymax <- rep(70,17)



time_ranges <- data.frame(
  xmin = xmin, 
  xmax = xmax, 
  ymin = ymin, 
  ymax = ymax,
  posture = c(rep(c("good", "transition", "bad", "transition"), 4), "good"))
```


## Plots by Participant



```{r}
instructed_agg %>%
  ggplot() +
  geom_line(aes(x = sec, y = angle_x, color = device_location)) +
  geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = posture), alpha = 0.4, data = time_ranges) +
  theme_minimal() +
  facet_wrap(~participant)
```


```{r}
instructed_agg %>%
  ggplot() +
  geom_line(aes(x = sec, y = angle_x, color = factor(participant))) +
  geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = posture), alpha = 0.4, data = time_ranges) +
  theme_minimal() +
  facet_wrap(~device_location)
```


## Data Modeling


### Lower Back

```{r}

### Lower Back


lmer_lb <- lmer(lower_back ~  posture + (1 + posture  | participant), data = model_data)

plot(lmer_lb)
qqnorm(residuals(lmer_lb))
qqline(residuals(lmer_lb))

lmer_log_lb <- lmer_lb <- lmer(log(lower_back + 6) ~  posture + (1 | participant), data = model_data)


glmer_lb <- glmer((lower_back + 20) ~  posture + (1 | participant), family = Gamma(link = "identity"), data = model_data)


plot(lmer_log_lb)

S(glmer_lb)
plot(glmer_lb)
```


#### glmer Model

```{r}
#| warning: false
custom_combos <- data.frame(
  posture = model_data$posture %>% unique()
)

custom_preds <- ref_grid(
  lmer_lb,
  data = custom_combos,
  cov.reduce = FALSE,
)

model_preds_lb <- emmeans(custom_preds, 
                         specs = ~ posture,
                         type = "response"
                         ) %>% 
  as_tibble()

model_preds_lb_pi <- predict(custom_preds, 
                         specs = ~ posture,
                         type = "response",
                         interval = "prediction"
                         ) %>% 
  as_tibble()

plot(custom_preds, PIs = TRUE, )

model_preds_lb %>%
  ggplot(aes(color = posture)) +

  # confidence interval
  geom_point(aes(y = posture, x = response), size = 3) +
  # geom_errorbar(aes(y = posture, xmin = asymp.LCL, xmax = asymp.UCL)) +
  geom_errorbar(aes(y = posture, xmin = lower.CL, xmax = upper.CL), width = 0, size = 2) +

  # prediction interval
  geom_point(data = model_preds_lb_pi,
             aes(y = posture, x = prediction)) +
  geom_errorbar(data = model_preds_lb_pi,
                aes(y = posture, xmin = lower.PL, xmax = upper.PL), width =0, size = 3, alpha = .4) +

  geom_vline(aes(xintercept = xint), lty = 2, color = "red", data = data.frame(xint = 0)) +
  
  # observed
  geom_point(data = model_data,
             aes(x = lower_back,
                 y = posture),
             alpha = 0.2) +
  theme_minimal() +
  labs(
    title = "LMM: Lower Back Sensor",
    x = "Angle X",
    y = "Posture"
    ) +
  theme(legend.position = "none",
        plot.title.position = "plot")

```



### Mid Back


```{r}
lmer_mb <- lmer(mid_back ~ posture + (1 | participant), data = model_data)

plot(lmer_mb)
qqnorm(residuals(lmer_mb))
qqline(residuals(lmer_mb))

glmer_mb <- glmer(mid_back+40 ~ posture + (1  | participant), family = Gamma(link = "identity"), data = model_data)



S(glmer_mb)
# Anova(glmer_mb)
plot(glmer_mb)
```



```{r}
#| warning: false
custom_combos <- data.frame(
  posture = model_data$posture %>% unique()
)

custom_preds <- ref_grid(
  lmer_mb,
  data = custom_combos,
  cov.reduce = FALSE,
)

model_preds_mb <- emmeans(custom_preds, 
                         specs = ~ posture,
                         type = "response"
                         ) %>% 
  as_tibble()

model_preds_mb_pi <- predict(custom_preds, 
                         specs = ~ posture,
                         type = "response",
                         interval = "prediction"
                         ) %>% 
  as_tibble()

plot(custom_preds, PIs = TRUE, )

model_preds_mb %>%
  ggplot(aes(color = posture)) +

  # confidence interval
  geom_point(aes(y = posture, x = emmean), size = 3) +
  # geom_errorbar(aes(y = posture, xmin = asymp.LCL, xmax = asymp.UCL)) +
  geom_errorbar(aes(y = posture, xmin = lower.CL, xmax = upper.CL), width = 0) +

  # prediction interval
  geom_point(data = model_preds_mb_pi,
             aes(y = posture, x = prediction)) +
  geom_errorbar(data = model_preds_mb_pi,
                aes(y = posture, xmin = lower.PL, xmax = upper.PL), width = 0, size = 2, alpha = .4) +

  geom_vline(aes(xintercept = xint), lty = 2, color = "red", data = data.frame(xint = 0)) +
  
  # observed
  geom_point(data = model_data,
             aes(x = mid_back,
                 y = posture),
             alpha = 0.2) +
  theme_minimal() +
  labs(
    title = "LMM: Mid Back Sensor",
    x = "Angle X",
    y = "Posture"
    ) +
  theme(legend.position = "none",
        plot.title.position = "plot")
```

### Neck


```{r}
lmer_n <- lmer(neck ~ posture + (1 | participant), data = model_data)

plot(lmer_n)
qqnorm(residuals(lmer_n))
qqline(residuals(lmer_n))


glmer_n <- glmer((neck*-1/10)+5 ~ posture + (1 | participant), family = Gamma(link = "identity"), data = model_data)


S(glmer_n)
Anova(glmer_n)
plot(glmer_n)
```

```{r}

#| warning: false
custom_combos <- data.frame(
  posture = model_data$posture %>% unique()
)

custom_preds <- ref_grid(
  lmer_n,
  data = custom_combos,
  cov.reduce = FALSE,
)

model_preds_n <- emmeans(custom_preds, 
                         specs = ~ posture,
                         type = "response"
                         ) %>% 
  as_tibble()

model_preds_n_pi <- predict(custom_preds, 
                         specs = ~ posture,
                         type = "response",
                         interval = "prediction"
                         ) %>% 
  as_tibble()

plot(custom_preds, PIs = TRUE)

model_preds_n %>%
  ggplot(aes(color = posture)) +

  # confidence interval
  geom_point(aes(y = posture, x = emmean), size = 3) +
  # geom_errorbar(aes(y = posture, xmin = asymp.LCL, xmax = asymp.UCL)) +
  geom_errorbar(aes(y = posture, xmin = lower.CL, xmax = upper.CL), width = 0) +

  # prediction interval
  geom_point(data = model_preds_n_pi,
             aes(y = posture, x = prediction)) +
  geom_errorbar(data = model_preds_n_pi,
                aes(y = posture, xmin = lower.PL, xmax = upper.PL), width = 0, size = 2, alpha = .4) +

  geom_vline(aes(xintercept = xint), lty = 2, color = "red", data = data.frame(xint = 0)) +
  
  # observed
  geom_point(data = model_data,
             aes(x = neck,
                 y = posture),
             alpha = 0.2) +
  theme_minimal() +
  labs(
    title = "LMM: Neck Sensor",
    x = "Angle X",
    y = "Posture"
    ) +
  theme(legend.position = "none",
        plot.title.position = "plot")
```

```{r}
lda_posture <- lda(posture ~ lower_back + mid_back + neck, data = model_data)
lda_posture


qda_posture <- qda(posture ~ lower_back + mid_back + neck, data = model_data)
qda_posture
```


```{r}
act_vs_pred <- model_data %>%
  drop_na() %>%
  mutate(
    posture = factor(posture),
    lda_pred = factor(predict(lda_posture)$class),
    qda_pred = factor(predict(qda_posture)$class)
  )


caret::confusionMatrix(data = act_vs_pred$lda_pred, reference = act_vs_pred$posture)

caret::confusionMatrix(data = act_vs_pred$qda_pred, reference = act_vs_pred$posture)

```
```{r}
lda_posture_preds <- model_data %>%
  drop_na() %>%
  bind_cols(
    predict(lda_posture)$posterior
  )
```

```{r}
model_data %>%
  drop_na() %>%
  bind_cols(
    as.matrix(model_data %>% dplyr::select(lower_back, mid_back, neck) %>%
  drop_na()) %*% lda_posture$scaling
  ) %>%
  ggplot() +
  geom_point(aes(x = LD1, y = LD2, color = posture)) + 
  theme_minimal()

model_data %>%
  drop_na() %>%
  bind_cols(
    as.matrix(model_data %>% dplyr::select(lower_back, mid_back, neck) %>%
  drop_na()) %*% lda_posture$scaling
  ) %>%
  ggplot() +
  geom_point(aes(x = LD1, y = LD3, color = posture)) + 
  theme_minimal()


model_data %>%
  drop_na() %>%
  bind_cols(
    as.matrix(model_data %>% dplyr::select(lower_back, mid_back, neck) %>%
  drop_na()) %*% lda_posture$scaling
  ) %>%
  ggplot() +
  geom_point(aes(x = LD2, y = LD3, color = posture)) + 
  theme_minimal()

```



